CREATE USER agroglobal_test WITH PASSWORD 'password' SUPERUSER CREATEDB;
GRANT ALL PRIVILEGES ON DATABASE agroglobal TO agroglobal_test;
\c agroglobal
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO agroglobal_test;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO agroglobal_test;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO agroglobal_test;
GRANT USAGE, CREATE ON SCHEMA public TO agroglobal_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO agroglobal_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO agroglobal_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO agroglobal_test;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TYPES TO agroglobal_test;
